source 'https://rubygems.org'

gem 'augeas'
gem 'colorize'
gem 'file-tail'
gem 'mysql2'
gem 'net-sftp', '3.0.0'
gem 'net-ssh', '6.1.0'
gem 'nori'
gem 'opennebula'
gem 'pg'
gem 'rake'
gem 'sequel'
gem 'sinatra-contrib'
gem 'sinatra-websocket'
gem 'ed25519', '1.2'
gem 'bcrypt_pbkdf', '1.0'
