# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
    paths:
      - 'ui/**'
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
        deployEnvironment:
          description: 'Deployment Environment'     
          required: true
          default: 'demo'

jobs:
  build_ui:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.deployEnvironment }}
    defaults:
      run:
        working-directory: ./ui

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
      
      - name: Dependencies
        run: npm install

      - name: Build
        env:
          VUE_APP_IONE_API_BASE_URL: ${{ secrets.IONE_API_BASE_URL }}
        run: npm run build

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@1.1
        with:
          # username
          username: ${{ secrets.SFTP_USER }}
          # your sftp server
          server: ${{ secrets.SFTP_HOST }}
          # your sftp server port, default to 22
          port: ${{ secrets.SFTP_PORT }}
          ssh_private_key: ${{ secrets.SFTP_PRIVATE_KEY }}
          # will put all file under this path
          local_path: ui/dist
          # files will copy to under remote_path
          remote_path: /usr/lib/one/ione/ui
