name: CD

on:
  workflow_dispatch:
    inputs:
        deployEnvironment:
          description: 'Deployment Environment'     
          required: true
          default: 'demo'

jobs:
  build_ione_admin_ui:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.deployEnvironment }}
    defaults:
      run:
        working-directory: ./ui

    steps:
      - uses: actions/checkout@v2.3.5
      - uses: actions/setup-node@v2.4.1
      
      - name: Dependencies
        run: npm install

      - name: Build
        env:
          VUE_APP_IONE_API_BASE_URL: ${{ secrets.IONE_API_BASE_URL }}
        run: npm run build

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: ${{ secrets.SFTP_USER }}
          server: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          ssh_private_key: ${{ secrets.SFTP_PRIVATE_KEY }}
          local_path: ui/dist
          remote_path: /usr/lib/one/ione/ui
  upgrade_ione:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.deployEnvironment }}
    
    steps:
      - uses: actions/checkout@v2.3.5

      - name: Remove unwanted dirs and files
        run: rm -rf docs modules ui

      - name: Upload codebase
        uses: appleboy/scp-action@master
        with:
          username: ${{ secrets.SFTP_USER }}
          host: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          source: "./*"
          target: /usr/lib/one/ione
      
      - name: Install gems, set hooks, upgrade service file and restart
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SFTP_USER }}
          host: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          script: |
            cd /usr/lib/one/ione
            chmod +x ione_server.rb
            chmod +x -R hooks/*
            rake hooks
            rake install_deps[yum, y]
            \cp -f sys/ione.service /usr/lib/systemd/system/ione.service
            systemctl daemon-reload
            systemctl restart ione
            sleep 10
            systemctl is-active ione
    