# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
    paths:
      - 'ui/**'
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
        deployEnvironment:
          description: 'Deployment Environment'     
          required: true
          default: 'demo'

jobs:
  # build_ione_admin_ui:
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: ${{ github.event.inputs.deployEnvironment }}
  #   defaults:
  #     run:
  #       working-directory: ./ui

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2.1.5
      
  #     - name: Dependencies
  #       run: npm install

  #     - name: Build
  #       env:
  #         VUE_APP_IONE_API_BASE_URL: ${{ secrets.IONE_API_BASE_URL }}
  #       run: npm run build

  #     - name: SFTP Deploy
  #       uses: wlixcc/SFTP-Deploy-Action@1.1
  #       with:
  #         # username
  #         username: ${{ secrets.SFTP_USER }}
  #         # your sftp server
  #         server: ${{ secrets.SFTP_HOST }}
  #         # your sftp server port, default to 22
  #         port: ${{ secrets.SFTP_PORT }}
  #         ssh_private_key: ${{ secrets.SFTP_PRIVATE_KEY }}
  #         # will put all file under this path
  #         local_path: ui/dist
  #         # files will copy to under remote_path
  #         remote_path: /usr/lib/one/ione/ui
  upgrade_ione:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.deployEnvironment }}
    
    steps:
      - uses: actions/checkout@v2

      - name: Remove unwanted dirs and files
        run: rm -rf docs modules ui

      - name: Test
        run: ls -l

      - name: Upload codebase
        uses: appleboy/scp-action@master
        with:
          username: ${{ secrets.SFTP_USER }}
          host: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          source: "./*"
          target: /usr/lib/one/ione
      
      - name: Install gems
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SFTP_USER }}
          host: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          script: |
            cd /usr/lib/one/ione
            chmod +x ione_server.rb
            chmod +x -R hooks/*
            rake hooks
            rake install_gems[y]
            \cp -f sys/ione.service /usr/lib/systemd/system/ione.service
            systemctl daemon-reload
            systemctl restart ione
            sleep 10
            systemctl is-active ione
    